{"name": "test_failing_equality", "status": "failed", "statusDetails": {"message": "AssertionError: 2 != 3 : 1 + 1 devrait être égal à 2, pas à 3", "trace": "self = <test_example.TestExampleFailure testMethod=test_failing_equality>\n\n    def test_failing_equality(self):\n        \"\"\"Test d'égalité qui échoue.\"\"\"\n>       self.assertEqual(1 + 1, 3, \"1 + 1 devrait être égal à 2, pas à 3\")\nE       AssertionError: 2 != 3 : 1 + 1 devrait être égal à 2, pas à 3\n\nexamples\\test_example.py:34: AssertionError"}, "description": "Test d'égalité qui échoue.", "start": 1744388815449, "stop": 1744388815449, "uuid": "618bfe99-a065-47c1-8b7c-0038f47b698c", "historyId": "843d4261a6383006bbf1ffd1f15be788", "testCaseId": "843d4261a6383006bbf1ffd1f15be788", "fullName": "examples.test_example.TestExampleFailure#test_failing_equality", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleFailure"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "2352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}