{"name": "test_name_error", "status": "broken", "statusDetails": {"message": "NameError: name 'undefined_variable' is not defined", "trace": "self = <test_example.TestExampleError testMethod=test_name_error>\n\n    def test_name_error(self):\n        \"\"\"Test qui gÃ©nÃ¨re une erreur de nom.\"\"\"\n>       return undefined_variable\nE       NameError: name 'undefined_variable' is not defined\n\nexamples\\test_example.py:59: NameError"}, "description": "Test qui gÃ©nÃ¨re une erreur de nom.", "start": 1744388486647, "stop": 1744388486648, "uuid": "9baddf7e-d727-4514-bb9e-a98b7a25bbad", "historyId": "1c0fc14c6e17317954c20df8f2328fb2", "testCaseId": "1c0fc14c6e17317954c20df8f2328fb2", "fullName": "examples.test_example.TestExampleError#test_name_error", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleError"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "16712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}