{"name": "test_failing_true", "status": "failed", "statusDetails": {"message": "AssertionError: False is not true : Cette assertion devrait Ã©chouer", "trace": "self = <test_example.TestExampleFailure testMethod=test_failing_true>\n\n    def test_failing_true(self):\n        \"\"\"Test de vÃ©ritÃ© qui Ã©choue.\"\"\"\n>       self.assertTrue(False, \"Cette assertion devrait Ã©chouer\")\nE       AssertionError: False is not true : Cette assertion devrait Ã©chouer\n\nexamples\\test_example.py:38: AssertionError"}, "description": "Test de vÃ©ritÃ© qui Ã©choue.", "start": 1744388815993, "stop": 1744388815994, "uuid": "0688a214-3d61-4a11-9791-2fb1801b7ecf", "historyId": "2109d6e791737383e292f5bf34531e8b", "testCaseId": "2109d6e791737383e292f5bf34531e8b", "fullName": "examples.test_example.TestExampleFailure#test_failing_true", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleFailure"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "2352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}