{"name": "test_failing_true", "status": "failed", "statusDetails": {"message": "AssertionError: False is not true : Cette assertion devrait Ã©chouer", "trace": "self = <test_example.TestExampleFailure testMethod=test_failing_true>\n\n    def test_failing_true(self):\n        \"\"\"Test de vÃ©ritÃ© qui Ã©choue.\"\"\"\n>       self.assertTrue(False, \"Cette assertion devrait Ã©chouer\")\nE       AssertionError: False is not true : Cette assertion devrait Ã©chouer\n\nexamples\\test_example.py:38: AssertionError"}, "description": "Test de vÃ©ritÃ© qui Ã©choue.", "start": 1744388741182, "stop": 1744388741182, "uuid": "25733391-0e7f-472d-b2cb-8752b9499fb4", "historyId": "2109d6e791737383e292f5bf34531e8b", "testCaseId": "2109d6e791737383e292f5bf34531e8b", "fullName": "examples.test_example.TestExampleFailure#test_failing_true", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleFailure"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "18216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}